baseURL = "https://www.veritasveniat.com"
title = "Veritas Veniat"

theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

## Change this two to switch between different language
languageCode = "en"           # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en" # For HTML page, now support: en, zh-hans, zh-hant, ja, nl, pl, it

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 10

[outputFormats]
[outputFormats.SearchIndex]
isPlainText = true
notAlternative = true
mediaType = "application/json"
path = "/search/"

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
author = "Nicolas Gabin"                # You can also set author in post front matter individually
subTitle = "Sleepy's Personal Blog"
defaultTheme = "dark"              # default theme when first visit (auto|dark|light)

# Source URL of the website, will appear in the footer
sourceURL = "https://github.com/usernametaken420/veritasVeniat"

# Word counter and read time indicator in post metadata
showWordCounter = false
showReadTime = true
hideNoTagList = false

# License in the footer
showLicenseInFooter = false

# License at the end of each post
showLicense = false
showToc = false

# Copyright
copyrightStartYear = "2022"

# Open Graph & Twitter Card variables
# You can also set description and images in post front matter individually
description = "A small blog for ramblings about Security and Testing"
# og = "/favicon.ico"                                          # This will use the image called og.png in static/img folder

# Posts shown in homepage
mainSections = ["posts"]

# Bangumi image chart id
# bgmImageChart = "000000"

# License
license = "CC BY-NC-SA 4.0"
licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Comments
# utterances, see: https://utteranc.es/
# utterancesRepo = "*/*"
# utterancesIssueTerm = "pathname"

# Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
# disqusShortname = "*********"
# Also use DisqusJS for accessing from Mainland China, see: https://github.com/SukkaW/DisqusJS
# If you want to set multiple api key, see theme's README for more details
# disqusJSApi = "https://*********/"
# disqusJSApikey = "**********"

# custom lazyload placeholder
# 16:9
lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
# 32:9
lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
# 8:9
lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

# Let images display in full brightness under dark mode
# disableDarkImage = true
#[params.assets]
#disableFingerprinting = true
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = true # Disable Hugo's code highlighter

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = "tags"

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "About"
url = "/about/"
weight = 3
[[menu.nav]]
name = "Salary Transparency"
url = "/salary"
weight = 4
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5

[[menu.link]]
name = "GitHub"
url = "https://github.com/UsernameTaken420"
weight = 1
[[menu.link]]
name = "Twitter"
url = "https://twitter.com/greenFrogzard"
weight = 2
[[menu.link]]
name = "Mastodon"
url = "https://infosec.exchange/@ragingGoblin"
rel = "me"
weight = 3

[build]
noJSConfigInAssets = false

[security]
enableInlineShortcodes = true
