# https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration

name = "Fuji"
license = "Apache-2.0"
licenselink = "https://github.com/dsrkafuu/hugo-theme-fuji/blob/master/LICENSE"
description = "A minimal Hugo theme."
homepage = "https://github.com/dsrkafuu/hugo-theme-fuji/"
demosite = "https://github.dsrkafuu.net/hugo-theme-fuji/"
tags = ["blog", "minimal", "responsive", "dark mode"]
features = ["blog", "minimal", "responsive", "dark mode"]

[author]
name = "DSRKafuU"
homepage = "https://dsrkafuu.net/"
